version: "3"

volumes:
  postgres_data:
      driver: local

services:
# # kafka
#   kafka:
#     image: confluentinc/cp-kafka:5.0.0-2
#     ports:
#       - 9092:9092
#     environment:
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#       KAFKA_BROKER_ID: 1
#     restart: on-failure
#   zookeeper:
#     image: confluentinc/cp-zookeeper:5.0.0-2
#     ports:
#       - 2181:2181
#     environment:
#       ZOOKEEPER_CLIENT_PORT: 2181
#redis
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
#db
  db:
    image: postgres:12-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
  adminer:
    image: adminer:4.7-standalone
    restart: always
    ports:
      - 8181:8080
